### ISSUE TITLE
[BUG] <网页面板打开失败>

### ISSUE THREAD

**Issue by yiteei** [ModuleList/akashaProxy#18]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查确认是由本模块造成，而不是clash或者自带的mosdns/AdGuardhome.

### 你的使用的root管理器是？

KernelSU

### 问题描述

因为我使用的是metacubexd面板，所以创建了ui文件夹并将metacubexd面板放入。

而模块webui貌似锁定了面板的路径为yacd，导致网页面板打开失败

### 模块日志

.

### 复现步骤

```bash
.
```

### 问题截图

![Screenshot_20240327-124616_KernelSU](https://github.com/ModuleList/akashaProxy/assets/77902908/aeed6866-6fe8-47bd-b296-ae17d6411972)

**Comment by heinu123** [comment]
提供clash.yaml配置内容

**Comment by ri-char** [comment]
检查config.yaml中的`external-ui`是否设置正确

**Comment by yiteei** [comment]
> 提供clash.yaml配置内容

[config.yaml.txt](https://github.com/ModuleList/akashaProxy/files/14767905/config.yaml.txt)
并没有设置错误

**Comment by yiteei** [comment]
> > 提供clash.yaml配置内容
> 
> [config.yaml.txt](https://github.com/ModuleList/akashaProxy/files/14767905/config.yaml.txt) 并没有设置错误

而在浏览器是正常打开的
