### ISSUE TITLE
[不兼容] 限制内存不可用

### ISSUE THREAD

**Issue by yiteei** [ModuleList/akashaProxy#22]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查确认是由本模块造成，而不是clash或者自带的mosdns/AdGuardhome.

### 你的使用的root管理器是？

KernelSU

### 问题描述

如题

### 模块日志

.

### 复现步骤

```bash
更改clash.config后执行“/data/clash/scripts/clash.tool -l”

更改clash.config后启动模块再执行“/data/clash/scripts/clash.tool -l”

都提示失败
```

### 问题截图

![图片注释](图片链接)
![Stitch_20240331_082423](https://github.com/ModuleList/akashaProxy/assets/77902908/18814018-871b-4355-b342-0252f2f2ac33)

**Comment by heinu123** [comment]
执行
```shell
mount | grep cgroup | awk '/memory/{print $3}' | head -1
```
看看

**Comment by yiteei** [comment]
> 执行
> 
> ```shell
> mount | grep cgroup | awk '/memory/{print $3}' | head -1
> ```
> 
> 看看

执行“mount | grep cgroup | awk '/memory/{print $3}' | head -1”后没有报错，之后执行“/data/clash/scripts/clash.tool -l”依旧报错

**Comment by heinu123** [comment]
> > 执行
> > ```shell
> > mount | grep cgroup | awk '/memory/{print $3}' | head -1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看看
> 
> 执行“mount | grep cgroup | awk '/memory/{print $3}' | head -1”后没有报错，之后执行“/data/clash/scripts/clash.tool -l”依旧报错

我没问你报不报错，我要看输出内容

**Comment by yiteei** [comment]
> > > 执行
> > > ```shell
> > > mount | grep cgroup | awk '/memory/{print $3}' | head -1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看看
> > 
> > 
> > 执行“mount | grep cgroup | awk '/memory/{print $3}' | head -1”后没有报错，之后执行“/data/clash/scripts/clash.tool -l”依旧报错
> 
> 我没问你报不报错，我要看输出内容

![Screenshot_20240331-161510_MT管理器](https://github.com/ModuleList/akashaProxy/assets/77902908/b89a53c2-a8d0-4da4-bb2b-8b32be3c467f)
什么都没有输出

**Comment by heinu123** [comment]
执行`mount`把内容上传，顺便报一下机型 安卓版本

**Comment by yiteei** [comment]
> 执行`mount`把内容上传，顺便报一下机型 安卓版本

[mount.txt](https://github.com/ModuleList/akashaProxy/files/14814788/mount.txt)
红米k40s 安卓14 类原生

**Comment by heinu123** [comment]
> > 执行`mount`把内容上传，顺便报一下机型 安卓版本
> 
> [mount.txt](https://github.com/ModuleList/akashaProxy/files/14814788/mount.txt) 红米k40s 安卓14 类原生

检查内核是否支持cgroup 并且检查/dev/memcg/目录是否存在
如果存在我会考虑获取不到目录的情况下默认设置Cgroup_memory_path路径为/dev/memcg/

**Comment by yiteei** [comment]
> > > 执行`mount`把内容上传，顺便报一下机型 安卓版本
> > 
> > 
> > [mount.txt](https://github.com/ModuleList/akashaProxy/files/14814788/mount.txt) 红米k40s 安卓14 类原生
> 
> 检查内核是否支持cgroup 并且检查/dev/memcg/目录是否存在 如果存在我会考虑获取不到目录的情况下默认设置Cgroup_memory_path路径为/dev/memcg/

![Screenshot_20240331-180448_MT管理器](https://github.com/ModuleList/akashaProxy/assets/77902908/ba8817df-54be-48f2-8fe9-880cca3d0eef)
是图里这样查看是否存在的吧

![Screenshot_20240331-180635_MT管理器](https://github.com/ModuleList/akashaProxy/assets/77902908/34184b2a-881c-4f1d-b265-38adccc099ad)
/dev/memcg/下有两个目录

**Comment by heinu123** [comment]
> > > > 执行`mount`把内容上传，顺便报一下机型 安卓版本
> > > 
> > > 
> > > [mount.txt](https://github.com/ModuleList/akashaProxy/files/14814788/mount.txt) 红米k40s 安卓14 类原生
> > 
> > 
> > 检查内核是否支持cgroup 并且检查/dev/memcg/目录是否存在 如果存在我会考虑获取不到目录的情况下默认设置Cgroup_memory_path路径为/dev/memcg/
> 
> ![Screenshot_20240331-180448_MT管理器](https://private-user-images.githubusercontent.com/77902908/318256690-ba8817df-54be-48f2-8fe9-880cca3d0eef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4ODAyODMsIm5iZiI6MTcxMTg3OTk4MywicGF0aCI6Ii83NzkwMjkwOC8zMTgyNTY2OTAtYmE4ODE3ZGYtNTRiZS00OGYyLThmZTktODgwY2NhM2QwZWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDEwMTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YmY5ODE5NTFiNTY3MWE2ZTIzMGRhZDc0YmY0Y2U2YWUyNGVjMzBjM2MwYTE1YzRjOTQ4MDc5MTk0NWJlOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dE13wDtk1JA9jVe6UWyWAQIFuZz2nTC9yMHNZD70oEk) 是图里这样查看是否存在的吧
> 
> ![Screenshot_20240331-180635_MT管理器] /dev/memcg/下有两个目录

敏感信息帮你删掉了，但是你设备似乎不支持cgroup限制内存
