### ISSUE TITLE
[invalid] <无法自动识别订阅链接>

### ISSUE THREAD

**Issue by 1991679126** [ModuleList/akashaProxy#23]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查确认是由本模块造成，而不是clash或者自带的mosdns/AdGuardhome.

### 你的使用的root管理器是？

KernelSU

### 问题描述

机场默认订阅无法识别 在订阅后加&flag=meta&types=all就可以了，应该是不会自动识别，希望开发者看到可以优化一下。clash Meta for Android就没有同样的问题。

### 模块日志

无

### 复现步骤

```bash
无
```

### 问题截图

![图片注释](图片链接)

**Comment by heinu123** [comment]
这是机场的问题，并且clashMeta[官方文档](https://wiki.metacubex.one/config/general/#ua)中也提到了如何自定义ua
