### ISSUE TITLE
在白名单模式下走代理的软件无网络

### ISSUE THREAD

**Issue by yzfycz** [ModuleList/akashaProxy#25]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查确认是由本模块造成，而不是clash或者自带的mosdns/AdGuardhome.

### 你的使用的root管理器是？

Magisk release

### 问题描述

在白名单模式，auto_config="true"，只要在packages.list里的软件都没网络，国内国外都没办法连接，一直转圈圈，黑名单模式正常，排除的软件也是正常无代理的，但白名单模式下就是我上面说的那种情况，看启动时输出的日志也是无报错的。

### 模块日志

无

### 复现步骤

```bash
白名单模式，auto_config="true"，packages.list一行一个包名，启动akashaProxy，打开被代理的软件，无网络。
```

### 问题截图

![图片注释](图片链接)

**Comment by heinu123** [comment]
完整配置在/data/clash/run/config.yaml 这是核心的问题

**Comment by yzfycz** [comment]
应该修改配置内的哪些内容呢，能不能麻烦大佬给说下，十分感谢
