### ISSUE TITLE
[BUG] <问题标题>只有一个机场，想用机场配置，但并没有找到Slipt变量

### ISSUE THREAD

**Issue by 82199691** [ModuleList/akashaProxy#30]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查确认是由本模块造成，而不是clash或者自带的mosdns/AdGuardhome.

### 你的使用的root管理器是？

Magisk release

### 问题描述

只有一个机场，想用机场配置，但并没有找到Slipt变量

### 模块日志

只有一个机场，想用机场配置，但并没有找到Slipt变量

### 复现步骤

```bash
.......只有一个机场，想用机场配置，但并没有找到Slipt变量
```

### 问题截图

![图片注释](图片链接)

**Comment by heinu123** [comment]
3月前已经移除了Slipt变量，不再分割配置文件。你可以理解为Slipt永久设置为false

**Comment by 82199691** [comment]
机场订阅转化为clash配置文件是静态的,直接替换config.yaml,节点该如何更新呢?
